### ISSUE TITLE
Manager Crashes After Dumping Icons

### ISSUE THREAD

**Issue by Gimzie** [SunTheCourier/SwitchPresence-Rewritten#10]
After selecting the option to dump icons, the manager application dumps each icon, then reports it is finished, and after a split-second, crashes. If run in applet mode, a full atmosphere crash is experienced, while under override mode, the software simply closes. (Likely typical behavior)

Here's a crash report:
[crash_report.log](https://github.com/SunTheCourier/SwitchPresence-Rewritten/files/3701003/crash_report.log)

**Comment by SunTheCourier** [comment]
Could you please test this build?
[SwitchPresence-Rewritten-Manager.zip](https://github.com/SunTheCourier/SwitchPresence-Rewritten/files/3715717/SwitchPresence-Rewritten-Manager.zip)

**Comment by SunTheCourier** [comment]
pinging @Gimzie

**Comment by Gimzie** [comment]
Sorry for the late reply, this build seems to take a little longer to dump all icons, but it doesn't crash, and appears to work fine.
