### ISSUE TITLE
Client Cannot Connect Via MAC Address After PC Reboot

### ISSUE THREAD

**Issue by Gimzie** [SunTheCourier/SwitchPresence-Rewritten#12]
After connecting to a Nintendo Switch running the sysmodule using a local IP address, the client application gives you an option to "Use MAC" instead, which should theoretically work regardless of what IP the Switch is currently using.

This does work in the short-term, but after a reboot, the application tells you that the MAC address is invalid, and the only way to connect again is by inputting the Switch's current IP. However, after doing this, connection via MAC address works fine until the next reboot.

**Comment by SunTheCourier** [comment]
I know @cathery wrote most of the MAC code but I don't know if they might know what's going on

**Comment by cathery** [comment]
oh yeah it's an oversight i found shortly after the last PR, it occurs when the switch can't find the specified mac address in the network. i pushed a commit in my fork to fix that, idk if you can push it yourself or if i should make another PR

**Comment by SunTheCourier** [comment]
I think i can make a PR from your repo, is this the commit your referencing? https://github.com/SunTheCourier/SwitchPresence-Rewritten/commit/dd54e566cbd1591d624b8e5a0c9b700dcac221fc

**Comment by cathery** [comment]
yeah that's it, i remember seeing a bug where the app crashes depending if your mac address was uppercase or lower case but i think it's fine now
