### ISSUE TITLE
switch-lan-play and SwitchPresence-Rewritten

### ISSUE THREAD

**Issue by iPAGod** [SunTheCourier/SwitchPresence-Rewritten#16]
Trying to connect my switch with SwitchPresence-Rewritten.exe using the mac address and the app crashes. I want to use it while connected to switch-lan-play but it crashes every time and I can't use the IP address of the switch because it has to have a custom one for switch-lan-play. Without switch-lan-play it works fine.

**Comment by SunTheCourier** [comment]
A combination like this typically will not work together at all but have you tried using the custom IP you set?

**Comment by iPAGod** [comment]
> A combination like this typically will not work together at all but have you tried using the custom IP you set?

I've tried with the custom IP and it wouldn't connect. If it is not possible then that's alright. Just wondering if it would of been possible.

**Comment by SunTheCourier** [comment]
Closing as there is no proper solution for this issue as far as I know.
