### ISSUE TITLE
CLI-only version

### ISSUE THREAD

**Issue by iomintz** [SunTheCourier/SwitchPresence-Rewritten#18]
I ported the WinForms client to a CLI app. I did this to make it easier for me to run on startup as a Linux user, and I figure it'll be handy to Windows users who would like to run it as a service, as well.
Here's my CLI port: https://github.com/iomintz/SwitchPresence-Rewritten/tree/cli-port

I'm wondering if this could somehow be integrated into the main project. Since both the GUI version and the CLI version are useful, the CLI version _could_ be added as a separate folder in the tree, but that would introduce needless code duplication. Maybe this could work as an MVC app, with a view for the GUI and a view for the CLI?

**Comment by SunTheCourier** [comment]
Though i'm not very found of how it was implemented from a quick glance I believe I could create a sort of "shared library" that both the CLI and GUI version can both use thus removing lots of possible code duplication and put it into 2 separate projects files, keeping it cleaner than putting it all into one project file.

**Comment by SunTheCourier** [comment]
If you would like to help start on that it would be much appreciated :) (do make sure to pr it as a draft too!)

**Comment by iomintz** [comment]
I'm not sure I'm adept enough at C# for that. This port was my first time working with the language.

**Comment by SunTheCourier** [comment]
[CLI SwitchPresence](https://github.com/SunTheCourier/SwitchPresence-Rewritten/files/3914655/CLI.zip)
[GUI SwitchPresence](https://github.com/SunTheCourier/SwitchPresence-Rewritten/files/3914659/GUI.zip)
:)

Please do test I have no clue if they work lol.

**Comment by iomintz** [comment]
```
➤ mono SwitchPresence-CLI.exe
Cannot open assembly 'SwitchPresence-CLI.exe': File does not contain a valid CIL image.
➤ file SwitchPresence-CLI.exe 
SwitchPresence-CLI.exe: PE32+ executable (console) x86-64, for MS Windows
```

The one you gave me fails because it's not compiled for my platform. But compiling it myself works fine :+1:

**Comment by SunTheCourier** [comment]
The application was built with DotNet core so try downloading that and running it with dotnet instead

**Comment by SunTheCourier** [comment]
i'll double check my compilation setting as well

**Comment by iomintz** [comment]
How do I "run it with dotnet"? `dotnet build` produces native executables for me. I have dotnet core installed, since it works for me when I compile it myself. I don't need to run my compiled copy with `dotnet` or anything, just the path to the executable.

**Comment by iomintz** [comment]
The command I used is `env FrameworkPathOverride=/usr/lib/mono/4.7.2-api/ dotnet build`. I am using Arch Linux.

**Comment by SunTheCourier** [comment]
ah my bad it should be a 'publish' version

**Comment by iomintz** [comment]
What does that mean?

**Comment by SunTheCourier** [comment]
VS allows you to compile it into two different ways one of them being a publish version which out a dll instead of an exe iirc

**Comment by iomintz** [comment]
So is that an error on your end or something I need to change?

**Comment by SunTheCourier** [comment]
you should be running the dll in the zip with `dotnet run`

**Comment by SunTheCourier** [comment]
My bad that actually might only be for windows, try this one instead 
[publish.zip](https://github.com/SunTheCourier/SwitchPresence-Rewritten/files/3924771/publish.zip)

**Comment by iomintz** [comment]
```
/tmp/foo
➤ dotnet run SwitchPresence-CLI.dll
Couldn't find a project to run. Ensure a project exists in /tmp/foo, or pass the path to the project using --project.
/tmp/foo
➤ file SwitchPresence-CLI.exe
SwitchPresence-CLI.exe: PE32+ executable (console) x86-64, for MS Windows
/tmp/foo
➤ file SwitchPresence-CLI.dll
SwitchPresence-CLI.dll: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows
/tmp/foo
➤ mono SwitchPresence-CLI.dll 

Unhandled Exception:
System.BadImageFormatException: Could not resolve field token 0x04000005, due to: Could not load type of field 'SwitchPresence_CLI.Program:timer' (0) due to: Could not resolve type with token 0100000d from typeref (expected class 'System.Timers.Timer' in assembly 'System.ComponentModel.TypeConverter, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.ComponentModel.TypeConverter, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Timers.Timer member:(null) assembly:/tmp/foo/SwitchPresence-CLI.dll type:Program member:(null)
File name: 'SwitchPresence-CLI'
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Could not resolve field token 0x04000005, due to: Could not load type of field 'SwitchPresence_CLI.Program:timer' (0) due to: Could not resolve type with token 0100000d from typeref (expected class 'System.Timers.Timer' in assembly 'System.ComponentModel.TypeConverter, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.ComponentModel.TypeConverter, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Timers.Timer member:(null) assembly:/tmp/foo/SwitchPresence-CLI.dll type:Program member:(null)
File name: 'SwitchPresence-CLI'
```

**Comment by SunTheCourier** [comment]
my bad it should be "dotnet <dll>"

**Comment by iomintz** [comment]
```
/tmp/tmp.6WE5t5Gao2
➤ dotnet SwitchPresence-CLI.exe
Error:
  An assembly specified in the application dependencies manifest (SwitchPresence-CLI.deps.json) has already been found but with a different file extension:
    package: 'SwitchPresence-CLI', version: '1.0.0'
    path: 'SwitchPresence-CLI.dll'
    previously found assembly: '/tmp/tmp.6WE5t5Gao2/SwitchPresence-CLI.exe'
```

**Comment by iomintz** [comment]
oh wait my bad, `dotnet SwitchPresence-CLI.dll` seems to work

**Comment by SunTheCourier** [comment]
uh i think something is wrong on your end try clearing temp?

**Comment by SunTheCourier** [comment]
oh ok

**Comment by SunTheCourier** [comment]
at it seems it functions i will be closing this issue and merging
