### ISSUE TITLE
Check if socket dies on the switch within the client

### ISSUE THREAD

**Issue by SunTheCourier** [SunTheCourier/SwitchPresence-Rewritten#2]
# Overview
When the socket dies (thru sleep or similar) the socket threading checking for packets seems to die(?) and must be manually aborted by the user. If possible look into solutions to abort the thread automatically and alert the user of the socket dying.

**Comment by Mithos23** [comment]
We basically have two possible ways to do this. 
1) we can check if we received any data (for example by comparing the magic of the titlepacket with 0)
2) we can send a byte to the switch which will trigger a SocketException when it fails

**Comment by SunTheCourier** [comment]
Our thread dies and no exception is triggered

**Comment by SunTheCourier** [comment]
Fixed by #3

**Comment by cathery** [comment]
For reference - the issue was the socket not having a receive timeout when calling Socket.Receive(). Setting Socket.ReceiveTimeout to any non-default value (infinite) fixes it
