### ISSUE TITLE
Enabling the Server at boot fails if the flags/ dir does not exist

### ISSUE THREAD

**Issue by iomintz** [SunTheCourier/SwitchPresence-Rewritten#21]
## Steps to reproduce
1. Make sure sdmc://atmosphere/titles/0100000000000464/flags/ does not exist.
2. Start the Manager program.
3. Enable the Server.
4. Reboot.

## Expected behavior

After reboot, the presence server is running, and the Manager program reports that the Server is enabled.

## Actual behavior

After reboot, the presence server is not running, and the Manager program reports that the Server is disabled.

## Remarks

I installed SwitchPresence-Rewritten through hbappstore, and this flag directory was not created for me.

v1.4.2

**Comment by SunTheCourier** [comment]
it already is?

**Comment by iomintz** [comment]
How can I get it to run at boot?
