### ISSUE TITLE
Does this require homebrew?

### ISSUE THREAD

**Issue by genderneutralnoun** [SunTheCourier/SwitchPresence-Rewritten#32]
Sorry if this isn't appropriate or whatever, but I can't find anywhere where it explicitly says whether or not it's homebrew-exclusive. I like playing online too much to risk my Switch getting banned, I've heard some intense stuff about the state of Switch homebrewing. If it is homebrew-exclusive, is there a feasible way for the same thing to be done with a stock console? I know very little about modding so forgive me.

**Comment by SunTheCourier** [comment]
This is homebrew exclusive but homebrew can not get you banned alone and it is fairly safe. If you want to set up homebrew you can check out [SDSetup](https://sdsetup.com/).

**Comment by iomintz** [comment]
https://nh-server.github.io/switch-guide/ also works. Make sure you set up emuMMC, which lets you dual boot hacks and non-hacks. As long as you only go online when not booted into hacks, you'll be fine.
