### ISSUE TITLE
Reading padding bytes is UB

### ISSUE THREAD

**Issue by leo60228** [SunTheCourier/SwitchPresence-Rewritten#6]
https://github.com/SunTheCourier/SwitchPresence-Rewritten/blob/master/Server/source/Sockets.cpp#L26 implicitly casts `packet` to a `void*` and reads all of its bytes. As `packet` contains padding, this is undefined behavior.

**Comment by SunTheCourier** [comment]
This is accounted for in the client, your welcome to change it to packed in a PR though. I have personally find issue with the PACKED macro and would rather kept as is as it presents no major issues.
