### ISSUE TITLE
[Suggestion] Linux/Mac builds?

### ISSUE THREAD

**Issue by einso** [SunTheCourier/SwitchPresence-Rewritten#8]
Wine crashes, as soon as I attempt to connect. A native Linux build would be very cool, if possible.

**Comment by SunTheCourier** [comment]
crash report?

**Comment by SunTheCourier** [comment]
also not sure about wine try mono?

**Comment by SunTheCourier** [comment]
And as recompilation for C# things is annoying on windows and not easily setup i will not be including builds for Linux/Mac but i will attempt to keep code compatible for Mono.

**Comment by einso** [comment]
Mono behaves in just the same way. I click connect, the window disappears. I dont have it set to minimize to tray either.

**Comment by SunTheCourier** [comment]
This might be related to some PRs downgrading the client might work as its been reported working before if it doesn't it's most likely mono missing Libs and some sort of crash report would help here
